version: "3.8"

services:
  andromeda:
    image: andromeda:latest # Thay bằng tên image Nextjs của bạn
    ports:
      - "3000:3000"
    depends_on:
      - orion

  orion:
    image: orion:latest # Thay bằng tên image Django của bạn
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    driver: bridge
